default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: personal_portfolio_development

test:
  <<: *default
  database: personal_portfolio_test

production:
  <<: *default
  database: personal_portfolio_production
  username: personal_portfolio
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
